### ISSUE TITLE
Using coord_sf(xlim = x,x2) with rotate = TRUE

### ISSUE THREAD

**Issue by calvinsbeale** [MikkoVihtakari/ggOceanMapsLargeData#2]
Hey Mikko,

I have found that I can't get coord_sf to work properly if rotate = TRUE is on. I can imagine it somehow changes the x axis but haven't worked out how to get around it. I was using the base ggplot function coord_sf(), after updating ggOceanMaps I tried using ggspatial::coord_sf but it also doesn't work. 
The reason I'm using rotate = TRUE is because the map I'm plotting crosses the anti-meridian - limits = c(172, -176, -40, -15)

This code works with rotate = FALSE but not if rotate = TRUE:
```
library(ggplot2)
library(ggOceanMaps)
library(ggspatial)

# Testing rotate = FALSE - adjusting the limits to not cross the anti-meridian
basemap(limits = c(172, 178, -40, -30), 
        rotate = FALSE,
        lat.interval = 1,
        lon.interval = 1,
        bathy.style = "rbb",
        legends = FALSE)+
  ggspatial::coord_sf(xlim = c(172,178), ylim = c(-40, -30), expand = FALSE)
# Plots the map correctly but doesn't cover the area I need

# Actual limits cross anti-meridian so rotate = TRUE
basemap(limits = c(172, -176, -40, -15), 
        rotate = TRUE,
        lat.interval = 1,
        lon.interval = 1,
        bathy.style = "rbb",
        legends = FALSE)+
  ggspatial::coord_sf(xlim = c(172,-176), ylim = c(-40, -15), expand = FALSE) # xlim doens't work!

```

I'm not sure it's really an issue for me anymore, I think the new updates have solved the issue I was having when I wrote that code, so maybe this doesn't need addressing, just thought I'd put it out here in case.

Thanks, Calvin

**Comment by MikkoVihtakari** [comment]
I might have misunderstand the issue. In the new version, you can plot across the antimeridian using decimal degrees. If antimeridian crossing is detected, `rotate` is automatically set to `TRUE` to circumvent certain issues. 

The following works on my machine:

```r
basemap(limits = c(172, -176, -40, -15),lat.interval = 1, lon.interval = 1,
 bathy.style = "rbb", legends = FALSE)
```
![image](https://github.com/MikkoVihtakari/ggOceanMapsLargeData/assets/4095204/26a73425-7e43-4b99-8b40-b501eb549f3f)

Is this what you want? 

The reason why `coord_sf()` does not work is because `rotate` modifies the CRS and limits. To make it work, you'll need to take the limits from the basemap object:

```r
p <-basemap(limits = c(172, -176, -40, -15))
p + coord_sf(xlim = attributes(p)$limits[c("xmin", "xmax")], 
ylim = attributes(p)$limits[c("ymin", "ymax")], expand = FALSE)
```

You can safely use `coord_sf()` from ggplot2. Dependency to ggspatial was removed when moving to v2.0.

On a related note, I have not added "downunder" rotate yet, because I have not needed it. Yet, it could be added in the future but programming it is not entirely straightforward and I do not have time to do it right now.

**Comment by calvinsbeale** [comment]
I have no issue plotting the maps, just using coord_sf. Thanks for clarifying how to do it.

Regarding ggspatial, I found that I have to use ggspatial for geom point and path, otherwise they don't plot correctly on the map. Here's a section of the track of points i'm plotting with a path between - m_track:
```

         Date Lon_daily_new Lat_daily_new tf month_d data_group
34 2019-04-08       177.950       -26.625 34   April          1
35 2019-04-09       178.325       -26.175 35   April          1
36 2019-04-10       178.675       -25.850 36   April          1
37 2019-04-11       179.075       -25.550 37   April          1
38 2019-04-12       179.350       -25.250 38   April          1
39 2019-04-13      -179.925       -24.825 39   April          1
40 2019-04-14      -179.425       -24.275 40   April          1
41 2019-04-15      -179.425       -23.700 41   April          1
42 2019-04-16      -179.375       -23.125 42   April          1
43 2019-04-17      -179.200       -22.750 43   April          1
```
In order for the points and track to correctly plot on the map I have to change geom_point and geom_path to ggspatial::
```
basemap(limits = c(172, -176, -40, -15), rotate = TRUE, lat.interval = 5, lon.interval = 2, bathy.style = "rbb", legends = FALSE) +
  geom_point(data = m_track, aes(x = Lon_daily_new, y= Lat_daily_new, colour = tf), group = 1, size = 1.4) +
  geom_path(data = m_track, aes(x = Lon_daily_new, y= Lat_daily_new, colour = tf), group = 1, linewidth = 1.2)+
  theme_bw()

# only plots correctly with ggspatial
basemap(limits = c(172, -176, -40, -15), rotate = TRUE, lat.interval = 5, lon.interval = 2, bathy.style = "rbb", legends = FALSE) +
  ggspatial::geom_spatial_point(data = m_track, aes(x = Lon_daily_new, y= Lat_daily_new, colour = tf), group = 1, size = 1.4) +
  ggspatial::geom_spatial_path(data = m_track, aes(x = Lon_daily_new, y= Lat_daily_new, colour = tf), group = 1, linewidth = 1.2)+
  theme_bw()
```

Is this a CRS issue again?

**Comment by MikkoVihtakari** [comment]
No, this is a feature rather than an issue. `rotate = TRUE` changes the CRS. Obviously, they'll get plotted in a different place when you do not transform them in the first option. ggspatial takes the CRS from basemap and transforms before plotting. See the [user manual](https://mikkovihtakari.github.io/ggOceanMaps/articles/ggOceanMaps.html#adding-data-to-maps). `transform_coord()` has a rotate argument, so that can be used too, but ggspatial is more convenient.
